# Este fluxo de trabalho fará uma instalação limpa das dependências do Node, cache/restore delas, construirá o código-fonte e executará testes em diferentes versões do Node
# Para mais informações, consulte: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Meu Projeto Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # Consulte o cronograma de lançamentos do Node.js em https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Usar Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Verificar cobertura de código
      run: npm run coverage
    - name: Verificar estilo de código
      run: npm run lint
    - name: Criar pacote
      run: npm run package
